import { useRef, useState } from "react";
import { Film, Image as ImageIcon, Plus, RotateCcw, Save, Trash2, X, ZoomIn, ZoomOut } from "lucide-react";
import { trpc } from "@/lib/trpc";

type SubtitleTrack = { language: string; subtitleUrl: string };
type Quality = { label: string; streamUrl: string; subtitleUrl: string; subtitleTracks: SubtitleTrack[] };
type Episode = { episodeNumber: number; name: string; subtitles: SubtitleTrack[]; qualities: Quality[] };
type VideoForm = { id?: number; name: string; logoUrl: string; description: string; sortOrder: string; isActive: boolean; allowPip: boolean; isFeatured: boolean; featuredEffect: "glow" | "pulse" | "ribbon" | "spark"; episodes: Episode[] };
const blankQuality = (): Quality => ({ label: "1080p", streamUrl: "", subtitleUrl: "", subtitleTracks: [] });
const blankEpisode = (number = 1): Episode => ({ episodeNumber: number, name: `Tập ${number}`, subtitles: [], qualities: [blankQuality()] });
const emptyForm: VideoForm = { name: "", logoUrl: "", description: "", sortOrder: "0", isActive: true, allowPip: true, isFeatured: false, featuredEffect: "glow", episodes: [blankEpisode()] };
const videoFieldStyle: React.CSSProperties = { minHeight: 46, width: "100%", boxSizing: "border-box", border: "1px solid rgba(210,243,107,.25)", borderRadius: 10, background: "#151a1d", color: "#fff", padding: "11px 13px" };
type LinkFilter = "all" | "online" | "unknown" | "offline";

export function AdminTvVideos() {
  const formRef = useRef<HTMLFormElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null);
  const [form, setForm] = useState<VideoForm>(emptyForm); const [queryText, setQueryText] = useState(""); const [linkFilter, setLinkFilter] = useState<LinkFilter>("all"); const [message, setMessage] = useState<string | null>(null);
  const [logoSource, setLogoSource] = useState(""); const [logoRotation, setLogoRotation] = useState(0); const [logoZoom, setLogoZoom] = useState(1); const [logoCrop, setLogoCrop] = useState(80);
  const videos = trpc.tv.adminVideos.useQuery(undefined, { refetchInterval: 5000, refetchOnWindowFocus: true }); const utils = trpc.useUtils();
  const create = trpc.tv.createVideo.useMutation({ onSuccess: async () => { setForm(emptyForm); setLogoSource(""); setMessage("Đã thêm video."); await utils.tv.adminVideos.invalidate(); }, onError: e => setMessage(e.message) });
  const update = trpc.tv.updateVideo.useMutation({ onSuccess: async () => { setForm(emptyForm); setLogoSource(""); setMessage("Đã cập nhật video."); await utils.tv.adminVideos.invalidate(); }, onError: e => setMessage(e.message) });
  const remove = trpc.tv.removeVideo.useMutation({ onSuccess: async () => { setMessage("Đã xóa video."); await utils.tv.adminVideos.invalidate(); } });
  const uploadLogo = trpc.tv.uploadPoster.useMutation({ onSuccess: url => { set("logoUrl", new URL(url, window.location.origin).toString()); setMessage("Đã lưu logo đã chỉnh sửa."); }, onError: e => setMessage(e.message) });
  const uploadSubtitle = trpc.tv.uploadSubtitle.useMutation({ onSuccess: () => setMessage("Đã tải phụ đề lên máy chủ."), onError: e => setMessage(e.message) });
  const busy = create.isPending || update.isPending || uploadLogo.isPending || uploadSubtitle.isPending;
  const set = <K extends keyof VideoForm>(key: K, value: VideoForm[K]) => setForm(current => ({ ...current, [key]: value }));
  const updateEpisode = (ei: number, fn: (episode: Episode) => Episode) => set("episodes", form.episodes.map((e, i) => i === ei ? fn(e) : e));
  const updateQuality = (ei: number, qi: number, fn: (quality: Quality) => Quality) => updateEpisode(ei, e => ({ ...e, qualities: e.qualities.map((q, i) => i === qi ? fn(q) : q) }));

  function uploadLogoFile(file?: File) { if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 8 * 1024 * 1024) { setMessage("Logo hỗ trợ JPG, PNG, WebP và nhỏ hơn 8MB."); return; } const reader = new FileReader(); reader.onload = () => { setLogoSource(String(reader.result)); setLogoRotation(0); setLogoZoom(1); }; reader.readAsDataURL(file); }
  function uploadSubtitleFile(file: File | undefined, ei: number, qi: number, ti?: number) { if (!file) return; const ext = file.name.toLowerCase().split(".").pop(); if (!["vtt", "srt"].includes(ext || "")) { setMessage("Phụ đề chỉ hỗ trợ .vtt hoặc .srt."); return; } const reader = new FileReader(); reader.onload = () => uploadSubtitle.mutate({ base64: String(reader.result), mimeType: "text/vtt" }, { onSuccess: url => ti === undefined ? updateQuality(ei, qi, q => ({ ...q, subtitleUrl: new URL(url, window.location.origin).toString() })) : updateQuality(ei, qi, q => ({ ...q, subtitleTracks: q.subtitleTracks.map((t, i) => i === ti ? { ...t, subtitleUrl: new URL(url, window.location.origin).toString() } : t) })) }); reader.readAsDataURL(file); }
  function applyLogoEdit() { if (!logoSource) return; const image = new Image(); image.onload = () => { const size = 900, canvas = canvasRef.current || document.createElement("canvas"); canvas.width = size; canvas.height = size; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.clearRect(0, 0, size, size); ctx.save(); ctx.translate(size / 2, size / 2); ctx.rotate(logoRotation * Math.PI / 180); const scale = Math.max(size / image.width, size / image.height) * logoZoom * (100 / logoCrop); ctx.drawImage(image, -image.width * scale / 2, -image.height * scale / 2, image.width * scale, image.height * scale); ctx.restore(); uploadLogo.mutate({ base64: canvas.toDataURL("image/png"), mimeType: "image/png" }); }; image.src = logoSource; }
  function submit(event: React.FormEvent) { event.preventDefault(); setMessage("Đang kiểm tra link video…"); const payload = { name: form.name, logoUrl: form.logoUrl || null, description: form.description || null, sortOrder: Number(form.sortOrder) || 0, isActive: form.isActive, allowPip: form.allowPip, isFeatured: form.isFeatured, featuredEffect: form.featuredEffect, episodes: form.episodes.map(e => ({ ...e, episodeNumber: Number(e.episodeNumber), name: e.name || `Tập ${e.episodeNumber}` })) }; if (form.id) update.mutate({ id: form.id, ...payload }); else create.mutate(payload); }
  function edit(video: any) { setForm({ id: video.id, name: video.name, logoUrl: video.logoUrl || "", description: video.description || "", sortOrder: String(video.sortOrder), isActive: video.isActive, allowPip: video.allowPip !== false, isFeatured: video.isFeatured === true, featuredEffect: video.featuredEffect || "glow", episodes: video.episodes.map((e: any) => ({ episodeNumber: e.episodeNumber, name: e.name, subtitles: (e.subtitles || []).filter((t: any) => t.language !== "Tiếng Việt").map((t: any) => ({ language: t.language, subtitleUrl: t.subtitleUrl || "" })), qualities: e.qualities.map((q: any) => ({ label: q.label, streamUrl: q.streamUrl, subtitleUrl: q.subtitleUrl || "", subtitleTracks: q.subtitleTracks || [] })) })) }); requestAnimationFrame(() => formRef.current?.scrollIntoView({ behavior: "smooth" })); }
  const allVideos = videos.data || []; const normalizedQuery = queryText.trim().toLocaleLowerCase("vi-VN");
  const filtered = allVideos.filter(video => { const searchable = [video.name, video.description || "", ...video.episodes.flatMap((e: any) => [e.name, ...e.qualities.flatMap((q: any) => [q.label, q.streamUrl])])].join(" ").toLocaleLowerCase("vi-VN"); const health = linkFilter === "all" || video.episodes.some((e: any) => e.qualities.some((q: any) => (q.healthStatus || "unknown") === linkFilter)); return (!normalizedQuery || searchable.includes(normalizedQuery)) && health; });
  const linkCounts = { all: allVideos.reduce((s, v) => s + v.episodes.reduce((n, e) => n + e.qualities.length, 0), 0), online: 0, unknown: 0, offline: 0 };
  allVideos.forEach(v => v.episodes.forEach((e: any) => e.qualities.forEach((q: any) => { const k = q.healthStatus || "unknown"; if (k in linkCounts) linkCounts[k as LinkFilter]++; })));
  const effectLabels = { glow: "Glow neon", pulse: "Pulse", ribbon: "Ribbon", spark: "Spark burst" };
  return <section className="admin-video-section">
    <div className="admin-video-title"><div><span className="eyebrow">VIDEO TRONG TRUYỀN HÌNH</span><h2>Đăng video / video dạng tập</h2><p>Mỗi chất lượng có danh sách ngôn ngữ subtitle riêng; logo có thể cắt, xoay, phóng to/thu nhỏ trước khi lưu.</p></div><Film size={28} /></div>
    <form ref={formRef} className="admin-video-form" onSubmit={submit}>
      <div className="admin-tv-form-heading"><div><strong>{form.id ? "Chỉnh sửa video" : "Thêm video mới"}</strong><span>Thêm nhiều tập, nhiều chất lượng và subtitle độc lập cho từng quality.</span></div>{form.id && <button type="button" className="button button-ghost" onClick={() => setForm(emptyForm)}><X size={15} /> Hủy sửa</button>}</div>
      <div className="admin-tv-grid"><label className="admin-video-field">Tên video<input style={videoFieldStyle} required value={form.name} onChange={e => set("name", e.target.value)} placeholder="Tên video" /></label><label className="admin-video-field">Upload ảnh logo<input style={videoFieldStyle} type="file" accept="image/jpeg,image/png,image/webp" onChange={e => uploadLogoFile(e.target.files?.[0])} /></label></div>
      {logoSource && <div className="logo-editor"><div className="logo-editor-preview"><img src={logoSource} alt="Xem trước logo" style={{ transform: `rotate(${logoRotation}deg) scale(${logoZoom})`, clipPath: `inset(${(100 - logoCrop) / 2}% round 14px)` }} /><span>Xem trước logo</span></div><div className="logo-editor-tools"><strong><ImageIcon size={15} /> Chỉnh sửa logo</strong><label>Cắt khung <input type="range" min="45" max="100" value={logoCrop} onChange={e => setLogoCrop(Number(e.target.value))} /></label><label>Phóng to / thu nhỏ <input type="range" min="0.5" max="2.5" step="0.05" value={logoZoom} onChange={e => setLogoZoom(Number(e.target.value))} /></label><div className="logo-editor-actions"><button type="button" className="button button-muted" onClick={() => setLogoZoom(z => Math.max(.5, z - .1))}><ZoomOut size={14} /></button><button type="button" className="button button-muted" onClick={() => setLogoZoom(z => Math.min(2.5, z + .1))}><ZoomIn size={14} /></button><button type="button" className="button button-muted" onClick={() => setLogoRotation(r => (r + 90) % 360)}><RotateCcw size={14} /> Xoay 90°</button><button type="button" className="button button-primary" onClick={applyLogoEdit} disabled={uploadLogo.isPending}>Lưu logo đã chỉnh sửa</button></div></div><canvas ref={canvasRef} hidden /></div>}
      <label className="admin-video-field">Logo URL<input style={videoFieldStyle} type="url" value={form.logoUrl} onChange={e => set("logoUrl", e.target.value)} placeholder="URL logo sau khi chỉnh sửa hoặc upload" /></label>
      <label className="admin-video-field">Mô tả<textarea style={videoFieldStyle} rows={2} value={form.description} onChange={e => set("description", e.target.value)} /></label>
      <div className="admin-tv-grid"><label className="admin-video-field">Thứ tự hiển thị<input style={videoFieldStyle} type="number" min="0" value={form.sortOrder} onChange={e => set("sortOrder", e.target.value)} /></label><div className="featured-editor"><label className="admin-tv-check"><input type="checkbox" checked={form.isFeatured} onChange={e => set("isFeatured", e.target.checked)} /><span>Hiển thị nổi bật trên app</span></label><select value={form.featuredEffect} onChange={e => set("featuredEffect", e.target.value as VideoForm["featuredEffect"])}>{Object.entries(effectLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><div className={`featured-effect-preview featured-effect-${form.featuredEffect}`}><span>{effectLabels[form.featuredEffect]}</span><b>VIDEO NỔI BẬT</b></div></div></div>
      <div className="admin-video-episodes"><div className="admin-video-subtitle"><strong>Các tập và chất lượng</strong><button type="button" className="button button-ghost" onClick={() => set("episodes", [...form.episodes, blankEpisode(form.episodes.length + 1)])}><Plus size={14} /> Thêm tập</button></div>
      {form.episodes.map((episode, ei) => <div className="admin-video-episode" key={ei}><div className="admin-tv-grid"><label className="admin-video-field">Số tập<input style={videoFieldStyle} type="number" min="1" value={episode.episodeNumber} onChange={e => updateEpisode(ei, x => ({ ...x, episodeNumber: Number(e.target.value) }))} /></label><label className="admin-video-field">Tên tập<input style={videoFieldStyle} value={episode.name} onChange={e => updateEpisode(ei, x => ({ ...x, name: e.target.value }))} /></label></div>
        <div className="quality-heading"><strong>Chất lượng và subtitle theo từng quality</strong><span>Quality mới có nút “Thêm ngôn ngữ sub” riêng</span></div>
        {episode.qualities.map((quality, qi) => <div className="quality-card" key={qi}><div className="quality-card-header"><b>{quality.label || `Quality ${qi + 1}`}</b>{episode.qualities.length > 1 && <button type="button" className="icon-button" onClick={() => updateEpisode(ei, x => ({ ...x, qualities: x.qualities.filter((_, i) => i !== qi) }))}><Trash2 size={15} /></button>}</div><div className="quality-main-grid"><input value={quality.label} aria-label="Chất lượng" placeholder="1080p" onChange={e => updateQuality(ei, qi, q => ({ ...q, label: e.target.value }))} /><input required type="url" value={quality.streamUrl} aria-label="Link video" placeholder="https://.../video.m3u8 hoặc .mp4" onChange={e => updateQuality(ei, qi, q => ({ ...q, streamUrl: e.target.value }))} /></div><label className="admin-video-quality-subtitle"><span>Phụ đề chính của {quality.label || "quality này"}</span><input type="url" value={quality.subtitleUrl} placeholder="URL VTT/SRT mặc định" onChange={e => updateQuality(ei, qi, q => ({ ...q, subtitleUrl: e.target.value }))} /><input type="file" accept=".vtt,.srt,text/vtt" onChange={e => uploadSubtitleFile(e.target.files?.[0], ei, qi)} /></label><div className="quality-subtitles"><div className="admin-video-subtitle"><strong>Ngôn ngữ sub cho {quality.label || "quality này"}</strong><button type="button" className="button button-muted" onClick={() => updateQuality(ei, qi, q => ({ ...q, subtitleTracks: [...q.subtitleTracks, { language: "English", subtitleUrl: "" }] }))}><Plus size={13} /> Thêm ngôn ngữ sub</button></div>{quality.subtitleTracks.map((track, ti) => <div className="subtitle-track-row" key={ti}><input value={track.language} placeholder="English / 한국어 / 中文" onChange={e => updateQuality(ei, qi, q => ({ ...q, subtitleTracks: q.subtitleTracks.map((t, i) => i === ti ? { ...t, language: e.target.value } : t) }))} /><input type="url" value={track.subtitleUrl} placeholder="URL phụ đề ngôn ngữ này" onChange={e => updateQuality(ei, qi, q => ({ ...q, subtitleTracks: q.subtitleTracks.map((t, i) => i === ti ? { ...t, subtitleUrl: e.target.value } : t) }))} /><input type="file" accept=".vtt,.srt,text/vtt" onChange={e => uploadSubtitleFile(e.target.files?.[0], ei, qi, ti)} /><button type="button" className="icon-button" onClick={() => updateQuality(ei, qi, q => ({ ...q, subtitleTracks: q.subtitleTracks.filter((_, i) => i !== ti) }))}><Trash2 size={15} /></button></div>)}</div></div>)}
        <button type="button" className="button button-muted" onClick={() => updateEpisode(ei, x => ({ ...x, qualities: [...x.qualities, blankQuality()] }))}><Plus size={13} /> Thêm chất lượng</button>{form.episodes.length > 1 && <button type="button" className="button button-danger" onClick={() => set("episodes", form.episodes.filter((_, i) => i !== ei))}><Trash2 size={13} /> Xóa tập</button>}
      </div>)}</div>
      <label className="admin-tv-check"><input type="checkbox" checked={form.isActive} onChange={e => set("isActive", e.target.checked)} /><span>Hiển thị trên app</span></label><label className="admin-tv-check"><input type="checkbox" checked={form.allowPip} onChange={e => set("allowPip", e.target.checked)} /><span>Cho phép Picture-in-Picture</span></label><button className="button button-primary" disabled={busy}><Save size={15} /> {busy ? "Đang xử lý…" : form.id ? "Lưu video" : "Kiểm tra và thêm video"}</button>{message && <p className="admin-tv-error">{message}</p>}
    </form>
    <div className="admin-video-list-head"><h3>DANH SÁCH VIDEO ĐÃ THÊM</h3><input value={queryText} onChange={e => setQueryText(e.target.value)} placeholder="Tìm video, tập, chất lượng hoặc link…" /></div><div className="admin-video-link-filters">{(["all", "online", "unknown", "offline"] as const).map(f => <button key={f} type="button" className={linkFilter === f ? "is-active" : ""} onClick={() => setLinkFilter(f)}>{f === "all" ? "Tất cả link" : f}<b>{linkCounts[f]}</b></button>)}</div><div className="admin-video-list admin-video-list-scroll">{videos.isLoading ? <p>Đang tải…</p> : filtered.length === 0 ? <div className="admin-tv-filter-empty">Không có video/link phù hợp.</div> : filtered.map(video => <article className="admin-video-item" key={video.id}><div><strong>{video.isFeatured ? "★ " : ""}{video.name}</strong><span>{video.description || "Không có mô tả"}</span><small>{video.episodes.length} tập · {video.episodes.reduce((n, e) => n + e.qualities.length, 0)} link quality · {video.isActive ? "Đang hiển thị" : "Đang ẩn"}</small></div><div className="admin-tv-actions"><button type="button" className="button button-primary" onClick={() => edit(video)}><Save size={14} /> Sửa</button><button type="button" className="button button-danger" onClick={() => { if (window.confirm(`Xóa video ${video.name}?`)) remove.mutate({ id: video.id }); }}><Trash2 size={14} /> Xóa</button></div></article>)}</div>
  </section>;
}
